blank_issues_enabled: true
contact_links:
  - name: Wolkenwalze Discussions
    url: https://github.com/wolkenwalze/community/discussions
    about: Provide feedback and suggestions, ask questions, and discuss with others
